Recipe App
vic778/Recipe-app pull request #25
Opened 2022-04-29 17:46 UTC by kingqabil

Followed the given UML Relationship Diagram.

Login page and registration page:

-Should be built with Devise.
Food list:

-Should display a list of food as in the wireframe.
-Should lead to the form that allows users to add new food.

Recipes list:

-Should display a list of recipes created by the logged-in user as in the wireframe.
-Should lead to recipe details.
-If the user is the owner of the recipe, should allow the user to delete it.

Public recipe list:

-Should display a list of all public recipes ordered by newest as in the wireframe.
-Should lead to recipe details.

Recipe details:

-If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
-If the user is the owner of the recipe, should lead to the form that allows the user to add new food.
-General shopping list view:
-Should show the list of food that is missing for all recipes of the logged-in user.
-Should count the total food items and total price of the missing food.
-Made sure there are no N+1 queries happening.
-Created a navigation menu that allows users to open all of the pages you created.
-Added unit and integration testing with RSpec and Capybara.
-Used Rails RESTful design and router.
-Added styling with Bootstrap.
-Added authorization rules with the cancancan gem

2022-04-29 18:10 UTC, DeliceLydia requested changes
## Hi Team, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there! Kudos on:
- An awesome UI
- Working on all features
- Good README



## Suggested changes
_Check the comments under the review._


### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-29 18:10 UTC, DeliceLydia commented on spec/requests/inventories_spec.rb
> +end
- [ ] Please fix failing tests
![test](https://user-images.githubusercontent.com/44745855/165999296-9051f0d2-ae44-4f24-b840-37801e5217f5.png)

2022-04-30 02:38 UTC, nevisende commented on spec/requests/inventories_spec.rb
> +end
Thank you for your review. We've fixed it now.

2022-04-30 02:57 UTC, rukundoeric approved these changes
Hi @vic778,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-30 03:26 UTC, nevisende commented
Thank you for your reviews :)

2022-04-30 03:26 UTC, closed without merging